set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

# DBus cross-compilation setup
set(VCPKG_CMAKE_CONFIGURE_OPTIONS
    -DDBUS_SESSION_SOCKET_DIR=/tmp
)
